name: "Run"

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: "0 * * * *"
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm ci
  #     - run: npm test

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
          username: narze
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
          username: Manoonchai
